# Generated by Django 5.1.1 on 2024-10-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_jobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='category',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=100, null=True),
        ),
    ]
