# Generated by Django 5.1.1 on 2024-10-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='Apply_Image',
            field=models.ImageField(null=True, upload_to='Media/Apply_Image'),
        ),
    ]
