# Generated by Django 5.1.1 on 2024-10-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_remove_jobmodel_skils_jobmodel_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('sing', 'Sing'), ('paly', 'Play'), ('hr', 'HR')], max_length=100, null=True),
        ),
    ]
