# Generated by Django 5.1.1 on 2024-10-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_remove_jobmodel_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='skils',
            new_name='skills',
        ),
    ]
