# Generated by Django 5.1.1 on 2024-10-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_seekerprofilemodel_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics Design'), ('cyber_security', 'Cyber Security')], max_length=100, null=True),
        ),
    ]
