# Generated by Django 5.2.4 on 2025-07-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='employer',
            new_name='recruiter',
        ),
    ]
