# Generated by Django 5.2.4 on 2025-07-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterApp', '0002_rename_employer_jobmodel_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
