# Generated by Django 5.2.4 on 2025-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingmodeel',
            name='profile',
            field=models.ImageField(null=True, upload_to='Profile/Students'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_profile',
            field=models.ImageField(null=True, upload_to='Profile/Students'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='teacher_profile',
            field=models.ImageField(null=True, upload_to='Profile/Teachers'),
        ),
    ]
