# Generated by Django 5.2.4 on 2025-07-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Position', models.CharField(choices=[('Administrative', 'Administrative'), ('StaffSupervision', 'StaffSupervision'), ('ResourceManagement', 'ResourceManagement'), ('Support', 'Support'), ('Staff', 'Staff')], max_length=50, null=True)),
                ('Date_ofJoining', models.DateField(null=True)),
                ('ProfilePicture', models.ImageField(null=True, upload_to='Media/ProfilePicture')),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OMS_app.departmentmodel')),
            ],
        ),
    ]
