# Generated by Django 5.2.4 on 2025-07-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS_app', '0002_departmentmodel_employeemanagementmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveType', models.CharField(choices=[('casual_leave', 'casual_leave'), ('sick_leave', 'sick_leave'), ('earned_leave', 'earned_leave'), ('annual_leave', 'annual_leave'), ('maternity_leave', 'maternity_leave')], max_length=100, null=True)),
                ('FromDate', models.DateField(null=True)),
                ('ToDate', models.DateField(null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')])),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OMS_app.employeemanagementmodel')),
            ],
        ),
    ]
