# Generated by Django 5.2.4 on 2025-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS_app', '0003_leavemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
