# Generated by Django 5.2.4 on 2025-07-26 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS_app', '0004_alter_leavemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemanagementmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
