# Generated by Django 5.0 on 2025-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingModeel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('profile', models.ImageField(null=True, upload_to='Media/Profile/Students')),
            ],
        ),
    ]
