# Generated by Django 5.2.4 on 2025-07-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingaccountmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
