# Generated by Django 5.2.4 on 2025-07-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofilemodel',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='Media/company_logos/'),
        ),
    ]
