# Generated by Django 5.2.4 on 2025-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('addrees', models.CharField(max_length=100, null=True)),
                ('profileImage', models.ImageField(null=True, upload_to='Media/profileImage')),
            ],
        ),
    ]
