# Generated by Django 5.2.4 on 2025-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentRoll', models.PositiveIntegerField(null=True)),
                ('StudentUsername', models.CharField(max_length=50, null=True)),
                ('StudentName', models.CharField(max_length=100, null=True)),
                ('StudentAge', models.IntegerField(null=True)),
                ('RegisterOfDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
