# Generated by Django 5.2.4 on 2025-08-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=10, null=True)),
                ('TeacherId', models.PositiveIntegerField(null=True)),
                ('TeacherAddress', models.TextField(null=True)),
                ('TeacherAge', models.PositiveIntegerField(null=True)),
                ('TeacherPic', models.ImageField(upload_to='Profile')),
            ],
        ),
    ]
