# Generated by Django 5.2.4 on 2025-08-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0002_teachermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='TeacherPic',
            field=models.ImageField(null=True, upload_to='Profile'),
        ),
    ]
