# Generated by Django 5.2.3 on 2025-07-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuthApp', '0002_pendingmodeel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100, null=True)),
                ('course_description', models.TextField(null=True)),
                ('course_duration', models.CharField(max_length=20, null=True)),
                ('course_Start_date', models.DateField(null=True)),
                ('course_fee', models.PositiveIntegerField(null=True)),
                ('assign_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher', to='UserAuthApp.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdmittedCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fee', models.PositiveIntegerField(null=True)),
                ('payment', models.PositiveIntegerField(null=True)),
                ('due', models.PositiveIntegerField(null=True)),
                ('admitted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_student', to='UserAuthApp.studentmodel')),
                ('admitted_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_course', to='CourseApp.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveIntegerField(null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('admitted_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_course_payment', to='CourseApp.coursemodel')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_student_payment', to='UserAuthApp.studentmodel')),
            ],
        ),
    ]
