# Generated by Django 5.0 on 2025-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
