# Generated by Django 5.0 on 2025-07-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNestApp', '0002_customusermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('deadline', models.DateField(null=True)),
                ('post_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
