# Generated by Django 5.0 on 2025-07-23 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNestApp', '0003_createjobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjobmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
