# Generated by Django 5.2.4 on 2025-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodels',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
