# Generated by Django 5.2.4 on 2025-07-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0003_userinfomodelstwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodelstwo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
