# Generated by Django 5.2.4 on 2025-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='studentRoll',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='studentUsername',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
