# Generated by Django 5.2.4 on 2025-07-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistorymodel',
            name='student',
        ),
        migrations.AlterField(
            model_name='paymenthistorymodel',
            name='admitted_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentCourse_info', to='courses.admittedcoursemodel'),
        ),
    ]
