# Generated by Django 5.2.5 on 2025-08-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='user_types',
            field=models.TextField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10, null=True),
        ),
    ]
